title: C++学习平台

remote_theme: just-the-docs/just-the-docs

mathjax: true

plugins:
  - jekyll-remote-theme

# 关键：定义文档集合
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# 默认应用到 docs
defaults:
  - scope:
      path: "docs"
      type: docs
    values:
      layout: default
      nav_order: 1

# 全局主题配置（可统一控制默认深浅色）
site_theme:
  default_mode: light # 可改为 dark
